### PR TITLE
Update to new versions for Grails 6.2.1 release

### PR DESCRIPTION
**Pull request by jamesfredley**
`grails-core` gets released before `grails-gradle-plugin` and references the next version of `grails-gradle-plugin`, which will be updated to reference the new `grails-core` release and then released

### CODE REVIEW

**Review by codeconsole — APPROVED** [review]

**Comment by rlconst** [comment]
Please publish to [maven ](https://mvnrepository.com/artifact/org.grails/grails-core)

**Comment by matrei** [comment]
@rlconst I believe it is published there. Maybe mvnrepository.com is not updated yet?
```console
$ mcs org.grails:grails-core
Searching for org.grails:grails-core...
Found 218 results (showing 20)

  Coordinates                        Last updated
  ===========                        ============
  org.grails:grails-core:6.2.1       04 Oct 2024 at 01:55 (CEST)
  org.grails:grails-core:6.2.0       05 Apr 2024 at 17:33 (CEST)
  org.grails:grails-core:6.1.2       31 Jan 2024 at 09:33 (CET)
  org.grails:grails-core:4.1.4       26 Jan 2024 at 10:04 (CET)
  org.grails:grails-core:5.3.6       09 Jan 2024 at 13:23 (CET)
  org.grails:grails-core:3.3.18      09 Jan 2024 at 12:34 (CET)
  org.grails:grails-core:5.3.5       19 Dec 2023 at 17:17 (CET)
  org.grails:grails-core:6.1.1       13 Dec 2023 at 15:40 (CET)
  org.grails:grails-core:3.3.17      07 Dec 2023 at 09:40 (CET)
  org.grails:grails-core:4.1.3       05 Dec 2023 at 15:13 (CET)
  org.grails:grails-core:5.3.4       30 Nov 2023 at 13:45 (CET)
  org.grails:grails-core:6.1.0       03 Nov 2023 at 17:05 (CET)
  org.grails:grails-core:6.0.0       24 Jul 2023 at 12:01 (CEST)
  org.grails:grails-core:5.3.3       11 Jul 2023 at 12:11 (CEST)
  org.grails:grails-core:6.0.0-RC1   22 May 2023 at 22:17 (CEST)
  org.grails:grails-core:6.0.0-M4    18 May 2023 at 19:05 (CEST)
  org.grails:grails-core:6.0.0-M3    12 May 2023 at 19:56 (CEST)
  org.grails:grails-core:6.0.0-M2    22 Mar 2023 at 18:54 (CET)
  org.grails:grails-core:5.3.2       14 Feb 2023 at 17:02 (CET)
  org.grails:grails-core:5.3.1       14 Feb 2023 at 15:38 (CET)
```

**Comment by matrei** [comment]
@rlconst I see now that `6.2.1` exists under the "Central" tab (https://mvnrepository.com/artifact/org.grails/grails-core?repo=central). I'm not sure why this has changed.

Is this what you are referring to when you say "Please publish to maven"?

**Comment by rlconst** [comment]
Didn't saw the central tab. Wondering what the difference. Sorry for bothering8 окт. 2024 г., в 15:19, Mattias Reichel ***@***.***> написал(а):﻿
@rlconst I see now that 6.2.1 exists under the "Central" tab (https://mvnrepository.com/artifact/org.grails/grails-core?repo=central). I'm not sure why this has changed.
Is this what you are referring to when you say "Please publish to maven"?

**Comment by jamesfredley** [comment]
The timing of these going to Central aligns with the requirement to use token based credentials to publish to OSSRH (s01.oss.sonatype.org).   

Scaffolding has had 3 releases since moving to token based credentials.  

https://s01.oss.sonatype.org/#nexus-search;gav~org.grails.plugins~scaffolding~~~

https://mvnrepository.com/artifact/org.grails.plugins/scaffolding?repo=central

**Comment by jamesfredley** [comment]
Older releases are certainly on central:  https://repo1.maven.org/maven2/org/grails/plugins/scaffolding/5.0.1/

So this might just be the way https://mvnrepository.com/ pulls or represents the data.

**Comment by matrei** [comment]
@jamesfredley Thanks for clearing that up!

**Pull request merged**
