### PR TITLE
Move GrailsFilters configuration from grails-spring to grails-web-common module so that grails-spring to is not required for grails-boot. 

### LINKED ISSUE #13854: Find new home for GrailsFilters class
### Feature description

Candidates:
```
unzip -l sample-apps/gsp/gsp-example/build/libs/gsp-example-7.0.0-SNAPSHOT.jar|grep \.jar|grep grails
    16894  11-18-2024 19:04   BOOT-INF/lib/grails-gsp-spring-boot-7.0.0-SNAPSHOT.jar
    52142  11-18-2024 18:44   BOOT-INF/lib/grails-plugin-sitemesh3-7.0.0-SNAPSHOT.jar
    13321  11-13-2024 23:35   BOOT-INF/lib/grails-web-gsp-taglib-7.0.0-SNAPSHOT.jar
   148775  11-13-2024 23:35   BOOT-INF/lib/grails-web-jsp-7.0.0-SNAPSHOT.jar
    81454  11-13-2024 23:35   BOOT-INF/lib/grails-web-gsp-7.0.0-SNAPSHOT.jar
    37040  11-13-2024 23:35   BOOT-INF/lib/grails-web-taglib-7.0.0-SNAPSHOT.jar
   187335  11-18-2024 18:44   BOOT-INF/lib/grails-web-common-7.0.0-SNAPSHOT.jar
   169566  11-13-2024 23:35   BOOT-INF/lib/grails-gsp-7.0.0-SNAPSHOT.jar
    96077  11-13-2024 23:35   BOOT-INF/lib/grails-taglib-7.0.0-SNAPSHOT.jar
   194500  11-18-2024 18:44   BOOT-INF/lib/grails-encoder-7.0.0-SNAPSHOT.jar
   732732  11-18-2024 18:44   BOOT-INF/lib/grails-core-7.0.0-SNAPSHOT.jar
    74203  11-18-2024 18:44   BOOT-INF/lib/grails-databinding-7.0.0-SNAPSHOT.jar
   259033  11-18-2024 18:43   BOOT-INF/lib/grails-bootstrap-7.0.0-SNAPSHOT.jar
   604186  11-18-2024 18:34   BOOT-INF/lib/grails-datastore-core-9.0.0-SNAPSHOT.jar
```

Without much thought, I am leaning toward` BOOT-INF/lib/grails-web-common-7.0.0-SNAPSHOT.jar`

### PR DESCRIPTION
**Pull request by codeconsole**
Fixes #13854 (See for discussion)

### CODE REVIEW

**Comment by matrei** [comment]
I'm trying to unravel this, help me out.

1. `GrailsFilters` was created in `grails-plugin-controllers` to house Servlet Filter order values. (ea6b1930a46eac6fde1440a2d9580f0c92bbe56c)
2. `GrailsFilters` was moved to `grails-spring` with motivation "Move GrailsFilters configuration to grails-spring module so that grails-plugin-controllers is not required.". (6f9d173e0af20a852971aad78a42cc42bba7fd80)
3. This PR moves `GrailsFilters` to `grails-web-common`. But the commit message says: "Move GrailsFilters configuration to grails-spring module so that grails-spring is not required for grails-boot."

I believe it is the commit message of step 3 that trips me up.

**Comment by codeconsole** [comment]
@matrei it was a typo.  if you look at the commit it is from -> to

**Comment by matrei** [comment]
This seems to blow up in  `grails-functional-tests`:
```console
         java.lang.NoClassDefFoundError: org/grails/spring/config/http/GrailsFilters
                at org.sitemesh.grails.plugins.sitemesh3.Sitemesh3GrailsPlugin.getDefaultPropertySource(Sitemesh3GrailsPlugin.groovy:35)
                at org.sitemesh.grails.plugins.sitemesh3.Sitemesh3GrailsPlugin.doWithSpring_closure2(Sitemesh3GrailsPlugin.groovy:63)
                at groovy.lang.Closure.call(Closure.java:433)
                at groovy.lang.Closure.call(Closure.java:412)
                at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
                at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
                at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
                at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:545)
                at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:152)
                at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:155)
                at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
                at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:148)
                at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:791)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:609)
                at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
                ... 25 more
```

**Comment by matrei** [comment]
As `GrailsFilters` is such a new class, I guess it has not been used in many places outside `grails-core` yet. But, I guess, `grails-plugin-sitemesh3` is one such place :smile: .

Try and update that right after merging this so we are back to working tests.

**Review by matrei — APPROVED** [review]

**Comment by codeconsole** [comment]
yes, the plugin is a required update.

**Pull request merged**
