### PR TITLE
Issue 12183 - Remove unnecessary test dependencies from build

### LINKED ISSUE #12183: Produced web application archive (gradle assemble) contains a lot of unnecessary dependencies
So, I am currently analyzing and upgrading some application dependencies, which appeared in our dependency check software. During the research I also discovered, that the resulting war file of a Grails application contains a lot of dependencies, which IMHO should not be part of a production web application artifact. For example, I personally would not expect it to contain anything that is related to CLI stuff or testing.

Some dependencies I found in the resulting artifact of a newly created Grails application were:
- Ant
- Picocli
- JUnit
-  TestNG
- spring-test
-  opentest4j

The list is not finite, there might be more.
This might also be related to https://github.com/grails/grails-core/issues/11753 which always includes H2 and HSQLDB even though it is not specified in `build.gradle`.

Is this expected?
Or am I missing something in my train of thought?

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `sdk install grails 5.0.1`
2. `sdk use grails 5.0.1`
3. `grails create-app myapp`
4.  `cd myapp`
5. `./gradlew assemble`

### Expected Behaviour

Production web archive should contain only necessary dependencies.

### Actual Behaviour

```
$ unzip -t ./build/libs/myapp-0.1.war | egrep 'ant|junit|picocli|opentest4j|spring-test|testng'
    testing: WEB-INF/lib/groovy-ant-3.0.7.jar   OK
    testing: WEB-INF/lib/groovy-cli-picocli-3.0.7.jar   OK
    testing: WEB-INF/lib/groovy-test-junit5-3.0.7.jar   OK
    testing: WEB-INF/lib/groovy-testng-3.0.7.jar   OK
    testing: WEB-INF/lib/spring-test-5.3.12.jar   OK
    testing: WEB-INF/lib/ant-junit-1.10.9.jar   OK
    testing: WEB-INF/lib/ant-1.10.12.jar   OK
    testing: WEB-INF/lib/junit-4.13.2.jar   OK
    testing: WEB-INF/lib/antlr-2.7.7.jar   OK
    testing: WEB-INF/lib/ant-launcher-1.10.12.jar   OK
    testing: WEB-INF/lib/ant-antlr-1.10.9.jar   OK
    testing: WEB-INF/lib/junit-platform-launcher-1.7.2.jar   OK
    testing: WEB-INF/lib/junit-jupiter-engine-5.7.2.jar   OK
    testing: WEB-INF/lib/junit-platform-engine-1.7.2.jar   OK
    testing: WEB-INF/lib/junit-jupiter-api-5.7.2.jar   OK
    testing: WEB-INF/lib/junit-platform-commons-1.7.2.jar   OK
    testing: WEB-INF/lib/picocli-4.6.1.jar   OK
    testing: WEB-INF/lib/testng-7.3.0.jar   OK
    testing: WEB-INF/lib/opentest4j-1.2.0.jar   OK
```

### Environment Information

- **Operating System**: Windows 11
- **Grails Version:** 5.0.1 (I think in Grails 4.x aswell)
- **JDK Version:** 11

### PR DESCRIPTION
**Pull request by yuri1969**
A quick attempt to resolve #12183. It was based on a Gradle dependency listing obtained from a 5.1.2 REST application.

Aimed to remove just the test-related dependencies.

* Removed unused `groovy-ant` from `grails-plugin-i18n`.
* Removed unused `junit` from `grails-plugin-url-mappings`.
* Upgraded `cache` plugin to solve `gpars`-related issues.
* Moved `spring-test` to the test source set.

Notes:
* Dependency constraint (marked as `(c)`) should be fine.
* BOM dependencies should also be fine.
* `GrailsWebMockUtil` was moved to the `grails-test` project - is it a correct location?

### CODE REVIEW

**Comment by manishkbharti** [comment]
@yuri1969 , @puneetbehl ,

`GrailsWebMockUtil ` is not accessible now because it moved from util to test.
I am using this file to change the locale for localization in a cron job.

Is there an alternative to this? Please suggest.

**Comment by puneetbehl** [comment]
@yuri1969 I have reverted this change and will do a Grails 5.1.5 release as this seems to break applications updating from 5.1.x. I think we should move this change to 5.2.x and have clean upgrade notes. 

@manishkbharti You should add the following dependency to build in order to resolve this:

```
testImplementation("org.grails:grails-test:${grailsVersion}")
```

**Comment by manishkbharti** [comment]
Thank you @puneetbehl 
Sure I'll use this dependency.

**Comment by yuri1969** [comment]
@puneetbehl You are right. The PR should go to the _5.2.x_ branch. Having a doc note at least describing impact of the scope change for `org.springframework.spring-test` would be nice. Would you do it?

**Pull request merged**
