### PR TITLE
Improvements for DefaultGrailsPlugin: set delegation strategy before …

### PR DESCRIPTION
**Pull request by rainboyan**
…calling doWithSpring Closure

If Grails plugin has defined invokeMethod, an error will occur when doWithSpring is executed

Forward port of [PR#12891](https://github.com/grails/grails-core/pull/12891) to 4.1.x

### CODE REVIEW

**Comment by puneetbehl** [comment]
@rainboyan Thank you for the pull-request. Could you please look into why the tests are failing?

Also, I will pull the changes for upstream branches so you do not need to create another pull-request for 5.3.x branch.

**Comment by rainboyan** [comment]
@puneetbehl I run `./gradlew test` on my local Mac,  all tests passed, and I think the errors were not related my PR.

**Comment by puneetbehl** [comment]
@rainboyan I am in the middle of something right now. I will take a look myself and get back to you. Thank you for the pull-request.

**Comment by rainboyan** [comment]
@puneetbehl thank you for your help!

**Comment by rainboyan** [comment]
@puneetbehl What's going on now? Any new releases planned for Grails 4?

**Comment by rainboyan** [comment]
@puneetbehl 
> Thank you for your pull-request. We only maintain the latest minor version which means the next release will be 4.1.3 and there will not be any 4.0.x release. So, I am closing this pull-request.

Waiting for your reply.

**Comment by puneetbehl** [comment]
The Grails 4 has already reached the EOL. Can you please rebase your changes to Grails 5 at minimum?

**Review by puneetbehl — CHANGES_REQUESTED** [review]
Please rebase the changes on top of Grails 5.

**Comment by rainboyan** [comment]
@puneetbehl Which branch of Grails 5 should I rebase?

Could you reopen the one of PRs
- https://github.com/grails/grails-core/pull/12893 
- https://github.com/grails/grails-core/pull/12894
- https://github.com/grails/grails-core/pull/12895

**Comment by puneetbehl** [comment]
Ideally, you should create your PR against the latest available stable version or default branch. Which should be the 6.0.x branch. 

However, we are maintaining two major versions Grails 5 and 6. In this scenario, you should create your PR based on latest branch for the specific major version. 

For example, if you are working on feature or bug-fix for version 5, create your branch based on the `5.3.x` branch (or whichever branch corresponds to the latest version within the 5.x.x series).

In the above, none of these PR's are based on 5.3.x or 6.0.x.

**Comment by rainboyan** [comment]
@puneetbehl Thank you for your reply.

When I submitted this PR seven months ago, Grails 4 was still under maintenance, and you closed the other PRs at that time, leaving only the current PR for 4.1.x. But now, you're telling me that Grails 4 is EOL, which is something I'm very upset about.

As a user, of course, I also hope that the PR will be merged into Grails 4, which will benefit many legacy projects that cannot be upgraded to Grails 5/6.

As a contributor, this was very disappointing, and it took seven months to reply that Grails 4 was no longer maintained. I can't understand this rash decision by the Grails management team.

If you think this PR is useful, I believe you have the way to deal with it, and it will be more appropriate for you to do it yourself, because you have the final decision on whether to merge or not, and choose the appropriate branch to merge. That's why I submitted multiple PRs in the first place, based on what I've seen before, it's often the case that PRs are submitted in a lower version but not merged into the next version.

**Comment by puneetbehl** [comment]
I want to apologize for the delay in responding to your Pull Request (PR) and any frustration it may have caused. When you submitted your PR seven months ago, Grails 4 was still under maintenance. The recent EOL announcement for Grails 4 understandably upset you.

Your desire to have your PR merged into Grails 4 is reasonable, especially for legacy projects. The delay in our response was disappointing, and we acknowledge the miscommunication. 

Your point about PRs submitted for lower versions not being merged into the next version is noted. We're committed to reevaluating your PR and finding a resolution that benefits the community.

We have the final say on merging, and we'll choose the appropriate branch for integration. We're dedicated to learning from this experience and improving our communication. I've created another PR #13150 which add your changes to Grails 5, and 6.

Your contributions are valued, and we're eager to collaborate to enhance the Grails framework for all users.

**Pull request closed without merging**
