### PR TITLE
Remove Micronaut Parent Context

### LINKED ISSUE #13549: Updating to latest version of Micronaut or remove the Micronaut Integration
see: https://github.com/orgs/grails/discussions/13517

### PR DESCRIPTION
**Pull request by codeconsole**
Requires https://github.com/grails/grails-testing-support/pull/421 for tests to work

### CODE REVIEW

**Comment by matrei** [comment]
Hmm..., was this PR ready to be merged?

**Comment by davydotcom** [comment]
yes

**Comment by matrei** [comment]
:smile: It's breaking the test suite, so now we can't do any other changes and rely on the tests

**Comment by jamesfredley** [comment]
After the merge and https://github.com/grails/grails-testing-support/pull/421#pullrequestreview-2329482851 being addressed, it revealed a number of currently failing tests on grails-core.  Here are some of the higher priority failures.  

DataBindingConfigurationSpec
[Test worker] ERROR grails.plugins.DefaultGrailsPluginManager - ERROR: Plugin [domainClass] cannot be loaded because its dependencies [['i18n']] cannot be resolved
[Test worker] ERROR grails.plugins.DefaultGrailsPluginManager - ERROR: Plugin [converters] cannot be loaded because its dependencies [['controllers', 'domainClass']] cannot be resolved
[Test worker] ERROR grails.plugins.DefaultGrailsPluginManager - ERROR: Plugin [mimeTypes] cannot be loaded because its dependencies [['core', 'controllers']] cannot be resolved

RespondMethodSpec
[Test worker] WARN org.grails.datastore.mapping.core.DatastoreUtils - Cannot unbind session, there's no SessionHolder registered

GrailsWebDataBinderConfigurationSpec
No signature of method: org.grails.spring.context.support.PluginAwareResourceBundleMessageSource.addMessage() is applicable for argument types: (String, Locale, String) values: [my.date.format, en_US, MMddyyyy]

GrailsUnitTestMixinGrailsApplicationAwareSpec
java.lang.NullPointerException: Cannot get property 'grailsApplication' on null object

**Pull request merged**
