### PR TITLE
I18nAutoConfiguration

### PR DESCRIPTION
**Pull request by codeconsole**
Resolves

```
Overriding bean definition for bean 'localeResolver' with a different definition: replacing [Root bean: class=null; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration; factoryMethodName=localeResolver; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration] with [Generic bean: class=org.springframework.web.servlet.i18n.SessionLocaleResolver; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null]
Overriding bean definition for bean 'messageSource' with a different definition: replacing [Root bean: class=null; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration; factoryMethodName=messageSource; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [org/springframework/boot/autoconfigure/context/MessageSourceAutoConfiguration.class]] with [Generic bean: class=org.grails.spring.context.support.PluginAwareResourceBundleMessageSource; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null]
```

Continuing the process, but going about it slowly not to break anything...

### CODE REVIEW

**Comment by matrei** [comment]
This branch currently fails in `grails-functional-tests`.

```groovy
     void "Test that switching language results in correct encodings"() {
         when:"the show page is rendered in german"
             go "/book/show/1?lang=de"
             println driver.pageSource
         then:"The language is correct"
             $('a', class:'create').text() == 'Book anlegen'
             $('input', class:'delete').@value == 'Löschen'
     }
```
```console
BookFunctionalSpec > Test that switching language results in correct encodings FAILED
    Condition not satisfied:

    $('a', class:'create').text() == 'Book anlegen'
    |                      |      |
    |                      |      false
    |                      |      11 differences (8% similarity)
    |                      |      (New-) (Book---)
    |                      |      (Book) (anlegen)
    |                      New Book
    [[[RemoteWebDriver: chrome on linux (aa76a1c57b7adbe2700eb5afe06537b6)] -> css selector: a.create]]
        at functionaltests.BookFunctionalSpec.Test that switching language results in correct encodings(BookFunctionalSpec.groovy:31)
```

**Comment by codeconsole** [comment]
> This branch currently fails in `grails-functional-tests`.

@matrei 
try now.  It was getting `localResolver` from somewhere else that inherited `WebMvcConfigurationSupport`

Looks like it was because of this:

https://github.com/grails/grails-core/blob/2a0b7d21305fb05fce181a91a83e99da55470b2b/grails-core/src/main/groovy/org/grails/compiler/injection/ApplicationClassInjector.groovy#L117-L119

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/issues/13843

**Review by matrei — APPROVED** [review]
According to my tests, Grails 7 built from this branch currently passes grails-functional-tests.

**Pull request merged**
