### PR TITLE
Issue #11318 apply Generated annotation to generated Controller Action

### PR DESCRIPTION
**Pull request by aulea**
apply Generated annotation to ControllerActionTransformer generated methods, to improve test coverage reports

### CODE REVIEW

**Comment by andersaaberg** [comment]
@aulea remember to sign the CLA so we can get this nice fix applied

**Comment by aulea** [comment]
I have now, but the badge is not updated. 
At least, when i follow the assignment link, then it says that i have agreed with it.

**Comment by andersaaberg** [comment]
@aulea : sorry for the late reply. It sounds very strange that the CLA does not update after your signature. I've tried it before, where I accidentally made the commit using my work email instead of my private email that I use for my Github account. Try to verify that the emailaddress in the commit matches your GitHub account - you can see the commit email address here: https://github.com/grails/grails-core/pull/12446/commits/9090187197d96cc0939feb69810e65b128015a01.patch

**Comment by aulea** [comment]
you were right, it was committed with different email address

**Comment by puneetbehl** [comment]
Thank you for the pull request. I am currently working on merging these changes manually. Also, I think we should use Groovy `org.apache.groovy.ast.tools.ClassUtils.addGeneratedMethod(ClassNode cNode, MethodNode mNode)` instead of explicitly calling `AnnotatedNodeUtils.markAsGenerated(classNode, method);`.

**Comment by puneetbehl** [comment]
Merged with 5b1e1c485e31c5a4bba127f4f1c157b4f95c5597

**Pull request closed without merging**
