### PR TITLE
fix #13867 - remove resolution strategy assignment and use default

### LINKED ISSUE #13867: Closure Resolution Strategy for doWithSpring()
### Issue description

History: 
* https://github.com/grails/grails-core/pull/13150 
* https://github.com/grails/grails-core/pull/13257/files

These changes have broken plugins like the DSL used in the database migration plugin: 
https://github.com/search?q=repo%3Agrails%2Fgrails-database-migration+delegate_first&type=code 

The decision was to revert the resolution strategy and let the default resolution strategy of the closure apply.

### PR DESCRIPTION
**Pull request by jdaugherty**
Per discussion in today's stewards meeting, this removes the resolution strategy assignment.

### CODE REVIEW

**Review by codeconsole — CHANGES_REQUESTED** [review]
welll... if you are going to delete line 549, how about you fix 546 and 547 to `} else {`
😉

**Review by codeconsole — APPROVED** [review]

**Comment by matrei** [comment]
@jdaugherty Can you merge `7.0.x` into this branch? I'm seeing `ClassNotFoundException: org.grails.spring.config.http.GrailsFilters` in `grails-functional-tests`. `GrailsFilters` has recently been moved to `org.grails.web.config.http.GrailsFilters`.

**Comment by jdaugherty** [comment]
@matrei this should be updated

**Comment by matrei** [comment]
Thanks!

**Review by matrei — APPROVED** [review]

**Pull request merged**
