### PR TITLE
Restore Grails Shell + add Spring Boot CLI classes that were removed in Spring Boot 3.0.0

### LINKED ISSUE #13569: Grails Shell for Grails 7
There is a need for Grails Shell 7 for Grails 7 to support plugins using Custom Scripts, other Custom Scripts, IntelliJ Grails Plugin including the Run Grails Command and all other plugin functionality, etc.  This will coexist with the new Forge CLI as time allows for migration of code and documentation to the new Forge and Gradle ways.  

Discussion:  https://github.com/orgs/grails/discussions/13562

PRs where grails-shell was removed. 
https://github.com/grails/grails-core/pull/13407/files 
https://github.com/grails/grails-gradle-plugin/pull/313/files 

https://youtrack.jetbrains.com/issue/IDEA-353327/IDE-does-not-recognize-Grails-6.2.0-projects
https://youtrack.jetbrains.com/issue/IDEA-327614/Idea-Intellij-does-not-recognize-a-project-with-grails-6
https://youtrack.jetbrains.com/issue/IDEA-351413/IntelliJ-IDEA-2024.1-fails-to-load-Grails-6.2.0-project-correctly
https://youtrack.jetbrains.com/issue/IDEA-356545/Grails-Resources-not-linkable-via-Editor-asset

https://github.com/grails/grails-core/issues/13523 - outstanding issue with using `gradlew runCommand -Pargs="generate-controller sampleapp.ClassA"`

### PR DESCRIPTION
**Pull request by jamesfredley**
Grails Shell 

Important to resolve https://github.com/spring-projects/spring-boot/commit/0555dda63d17bbd4364c4eb2268da27480be4d05#diff-26fb6a79071ed389aa8e3ffe28cc8b0d171930c4e9a5277357170704e52f32c6 which is needed for gorm-hibernate5

### CODE REVIEW

**Comment by jamesfredley** [comment]
I'll work on the build issue tomorrow

**Comment by codeconsole** [comment]
The title of the pull request is "merge6.2.x into 7.0.x "

The only thing I don't really like about this is combining the merge with adding the Spring Boot CLI.   There is no clean way to revert any of this.  From what you posted, that looks like the CLI commands were removed in 3.4.x, but 3.4.x isn't even out yet.   7.0.x is currently based off of `springBootVersion=3.2.6`     Can we break this up a little more?  Maybe do the merge first, then add the CLI ?

**Comment by jamesfredley** [comment]
@codeconsole let's do a normal merge instead of squash and merge to keep the merge commit and the other 2 new commits that will allow a clean revert.  At the merge commit, the build was failing, because the Spring Boot cli classes were removed in v3.0.0-M5 (github collapses the list of tags).

https://github.com/grails/grails-core/pull/13585/commits

**Comment by matrei** [comment]
Do we need all these changes/commits in 7.0.x?

**Comment by jamesfredley** [comment]
We could remove some of these classes, but may need them back down the road as we require the functionality, given we can no longer get them from org.springframework.boot:spring-boot-cli: as of 3.0.0.  Currently grails-shell and gorm-hibernate5 need a portion of these classes.  I have not dug into the other repos to see where we were using org.springframework.boot.cli.*

This PR is the liberal approach.

**Comment by jamesfredley** [comment]
grails-wrapper was the only other reference to org.springframework.boot.cli.*

**Review by matrei — APPROVED** [review]

**Pull request merged**
