### PR TITLE
Add minimum Java version so the grails forge cli can pull that property instead of defaulting based on its own version

### PR DESCRIPTION
**Pull request by jdaugherty**

### CODE REVIEW

**Comment by jdaugherty** [comment]
I have an associated 7.0.0 branch here:  jdaugherty:feature/7.0.0/pomJavaVersion

**Comment by jdaugherty** [comment]
Closing this, we're going to default the version in the cli instead.

**Comment by codeconsole** [comment]
@jdaugherty couldn't you have just pulled this from spring?  The spring-bom is imported using the grails-gradle-plugin and I am pretty sure spring has a parent pom with this same information

**Comment by jdaugherty** [comment]
Probably but we don't really need to make it that complicated because either way we have to update the JdkVersion enum in the cli project and there was already a placeholder for the default

**Comment by codeconsole** [comment]
actually, that wouldn't have worked because Spring went from 8 > 17

**Pull request closed without merging**
